# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - left_hand_controller
    - right_hand_controller

  left_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - LJ1
      - LJ2
      - LJ3
      - LJ4
      - LJ5
      - LJ6
    action_ns: follow_joint_trajectory
    default: true
  right_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - RJ1
      - RJ2
      - RJ3
      - RJ4
      - RJ5
      - RJ6
    action_ns: follow_joint_trajectory
    default: true
  left_hand_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - LJ7
    action_ns: follow_joint_trajectory
    default: true
  right_hand_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - RJ7
    action_ns: follow_joint_trajectory
    default: true